/* Generated by Cython 0.29.35 */

#ifndef __PYX_HAVE__wrapper_cython_B
#define __PYX_HAVE__wrapper_cython_B

#include "Python.h"

#ifndef __PYX_HAVE_API__wrapper_cython_B

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int i;

#endif /* !__PYX_HAVE_API__wrapper_cython_B */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initwrapper_cython_B(void);
#else
PyMODINIT_FUNC PyInit_wrapper_cython_B(void);
#endif

#endif /* !__PYX_HAVE__wrapper_cython_B */
